name: ShellCheck
on: [push,pull_request]
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ludeeus/action-shellcheck@v1
        with:
          paths: |
            bin/*.sh
            scripts/*.sh
